### ISSUE TITLE
BUG WITH THIS NEW VERSION PLUGIN

### ISSUE THREAD

**Issue by lennonfuston** [dpa99c/cordova-sqlite-porter#37] opened 2018-07-04 02:05 UTC
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] documentation issue

- [ ] feature request

# Bug report

**Current behavior:**

Ionic3
On iOS don't show erros, but importJsonToDb and importSqlToDb don't work.
On Android show a error: 
:8100/plugins/uk.co.workingedge.cordova.plugin.sqliteporter/www/sqlitePorter.js:649 Uncaught SyntaxError: missing ) after argument list
polyfills.js:3 Uncaught Error: Module uk.co.workingedge.cordova.plugin.sqliteporter.sqlitePorter does not exist.

**Expected behavior:**
Import .sql or .json to .db

**Steps to reproduce:**
Create a new empty project ionic3, install plugin and try to import .sql or .json

**Environment information**
MacBook Pro HIGH-SIERRA 10.13.5 - (Retina, 13-inch, Early 2015) 2,7 GHz Intel Core i5, 8 GB 1867 MHz DDR3

- Cordova CLI version 
	- 8.0.0
- Cordova platform version
	- Installed platforms:
  android 7.0.0
  ios 4.5.4
Available platforms:
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
- Plugins & versions installed in project (including this plugin)
    cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
onesignal-cordova-plugin 2.4.0 "OneSignal Push Notifications"
uk.co.workingedge.cordova.plugin.sqliteporter 1.0.3 "sqlite porter"
- Dev machine OS and version, e.g.
    - OSX
        ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77

_Runtime issue_
- Device details
    - iPhone X Simulator
- OS details
    - Android 7.0.1_
	
_Android build issue:_	
- Node JS version
    - v10.1.0
- Gradle version
	- 4.1			4.6			buildOutputCleanup
- Target Android SDK version
	- 16
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - v10.1.0
- XCode version Version 9.4.1 (9F2000)

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v10.1.0
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : /Users/user/Library/Android/sdk

Misc:

    backend : pro
- Installed Ionic Native modules and versions
    ├── @ionic-native/core@4.7.0
├── @ionic-native/device@4.7.0
├── @ionic-native/file@4.7.0
├── @ionic-native/in-app-browser@4.7.0
├── @ionic-native/in-app-purchase@4.9.0
├── @ionic-native/onesignal@4.9.0
├── @ionic-native/splash-screen@4.7.0
├── @ionic-native/sqlite@4.9.0
├── @ionic-native/sqlite-porter@4.9.0
├── @ionic-native/status-bar@4.7.0

**Related code:**
this.sqlitePorter.importSqlToDb()

**Console output**
none

**Other information:**
I see the file sqlitePorter.js and they have a new function to remove comments maybe this new version came out with bug.

# Feature request

# Documentation issue

**Comment by dpa99c** [comment] 2018-07-04 06:30
Thanks for reporting this, yes it appears to be caused by #36, specifically [here](https://github.com/dpa99c/cordova-sqlite-porter/pull/36/files#diff-2275597cab287a4606bfce80178b3680R648) where an ES6 arrow function has been used. I think replacing with an ES5 function will fix it.

**Comment by dpa99c** [comment] 2018-07-04 06:36
Fix has been published to npm in v1.0.4

**Closed as completed** 2018-07-04 06:36 UTC
